server.port=8761
spring.application.name=eureka-server

# Eureka cluster (3 VMs)
eureka.client.service-url.defaultZone=http://vm-node-a.platform:8761/eureka,http://vm-node-b.platform:8761/eureka,http://vm-node-c.platform:8761/eureka

# Allow it to act as both server + client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==============================
# CONFIG SERVER
# ==============================
spring.config.import=optional:configserver:http://config.platform:8888

# ==============================
# SERVER
# ==============================
server.address=0.0.0.0


# IMPORTANT (avoid localhost issue)
eureka.instance.prefer-ip-address=true

# ==============================
# MANAGEMENT (ACTUATOR)
# ==============================
management.endpoints.web.exposure.include=*