server.port=8761
spring.application.name=eureka-server

# Eureka cluster (3 VMs)
eureka.client.service-url.defaultZone=http://vm-node-a.platform:8761/eureka,http://vm-node-b.platform:8761/eureka,http://vm-node-c.platform:8761/eureka

# Allow it to act as both server + client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true